Fix out-of-bounds memcpy
adrian-thurston/colm pull request #137
Opened 2021-11-30 00:38 UTC by viccie30

`memcpy` in `string_alloc_full` was copying 32 bytes, while the string is only 25 bytes including the terminating null byte.

Also, since this is a string literal, there is no need to actually copy it. Just allocating a head is enough if I'm reading the code correctly. This was also found by building with LTO enabled.

2021-12-02 23:57 UTC, adrian-thurston requested changes
Thanks for reporting this!

For consistency I'd like to keep the errors allocated. They can live beyond the execution of the colm program. The pointer strings I'd like to reserve for pointing into the input buffer. This will help with memory management of the input buffers.

Also, I would prefer the use of a `const char*` for specifying the string before using it twice. I think it's much more readable.

2021-12-02 23:58 UTC, viccie30 commented
Thanks for the review! I'll make the changes tomorrow and push them.

2021-12-03 11:10 UTC, viccie30 commented
I've force pushed the changes you requested. Please let me know if it needs more work.

2021-12-03 19:04 UTC, adrian-thurston approved these changes

2021-12-03 19:06 UTC, merged